import type { Metadata } from "next";
import { Geist_Mono , Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import { ToastContainer } from 'react-toastify';

const plusJakarta_Sans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta_Sans.variable} ${geistMono.variable} `}
      >
        <Navbar/>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
